# from blockwise_parallel.blockwise_paralle import BlockwiseParallelTransformerAttention
# from blockwise_parallel.test1 import BlockwiseParallelTransformer/
from blockwise_parallel.jax_v1 import BlockwiseParallelTransformerAttention